site_name: Run:AI Documentation Library
site_url: https://docs.run.ai/
copyright: Copyright © 2020 - 2021 Run:AI
google_analytics:
  - UA-122651141-1
  - auto
repo_url: https://github.com/run-ai/docs/
docs_dir: docs 
theme: 
  name: material
  custom_dir: overrides
  language: en
  favicon: images/favicon.ico
  logo: images/runai-logo2.svg
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
strict: true
markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: True
#  - pymdownx.tasklist:
 #     custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/runailabs
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/runailabs/
plugins:
  - search
  - git-revision-date-localized
  - render_swagger
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'Administrator/Admin-User-Interface-Setup/Working-with-Projects.md' : 'Administrator/admin-ui-setup/project-setup.md'
        'Administrator/Admin-User-Interface-Setup/Working-with-Departments.md' : 'Administrator/admin-ui-setup/department-setup.md'
        'Researcher/scheduling/The-Run-AI-Scheduler.md' : 'Researcher/scheduling/the-runai-scheduler.md'
        'home/whats-new.md' : 'home/whats-new-2021.md'
nav:
  - Home: 
    - 'Overview': 'index.md'
    - 'System Components' : 'home/components.md'
    - 'Whats New 2021' : 'home/whats-new-2021.md'
    - 'Whats New 2020' : 'home/whats-new-2020.md'
  - 'Administrator' :
    - 'Overview' : 'Administrator/overview-administrator.md'
    - 'Run:AI Setup' : 
      - 'Installation Types' : 'Administrator/runai-setup/installation-types.md'
      - 'Classic (SaaS)' :
        - 'Introduction' : 'Administrator/Cluster-Setup/cluster-setup-intro.md'
        - 'Prerequisites' : 'Administrator/Cluster-Setup/cluster-prerequisites.md'
        - 'Cluster Install' : 'Administrator/Cluster-Setup/cluster-install.md'
        - 'Customize Installation' : 'Administrator/Cluster-Setup/customize-cluster-install.md'
        - 'Cluster Upgrade' : 'Administrator/Cluster-Setup/cluster-upgrade.md'
        - 'Cluster Delete' : 'Administrator/Cluster-Setup/cluster-delete.md'
        - 'Kubernetes Install' : 'Administrator/Cluster-Setup/install-k8s.md'  
        - 'Quick Single Node Install' : 'Administrator/Cluster-Setup/single-node-install.md'    
        - 'Troubleshooting' : 'Administrator/Cluster-Setup/cluster-troubleshooting.md'
        - 'Advanced' :
          - 'Allow external access to Containers' : 'Administrator/Cluster-Setup/allow-external-access-to-containers.md'
          # - 'Configure an HTTP Proxy Server ' : 'Administrator/Cluster-Setup/proxy-server.md'
          - 'Authentication and Authorization' : 'Administrator/Cluster-Setup/researcher-authentication.md'
          - 'LDAP Authentication' : 'Administrator/Cluster-Setup/ldap-integration.md'
          - 'Understanding Cluster Access Roles' : 'Administrator/Cluster-Setup/access-roles.md'
          - 'NVIDIA Drivers' : 'Administrator/Cluster-Setup/nvidia.md'
          - 'User Identity in Container' : 'Administrator/Cluster-Setup/non-root-containers.md'
          - 'Node Downtime' : 'Administrator/Cluster-Setup/node-downtime.md'
          - 'Set Node Roles' : 'Administrator/Cluster-Setup/node-roles.md'
          - 'Install Administrator CLI' : 'Administrator/Cluster-Setup/cli-admin-install.md'
          - 'Kubernetes Best Practices' : 'Administrator/Cluster-Setup/kubernetes-config-best-practices.md'
      - 'Self-hosted' : 
        - 'Overview' : 'Administrator/runai-setup/self-hosted/overview.md'
        - 'Kubernetes-based' :
#          - 'Overview' : 'Administrator/runai-setup/self-hosted/k8s/overview.md'
          - 'Prerequisites' : 'Administrator/runai-setup/self-hosted/k8s/prerequisites.md'
          - 'Preperations' : 'Administrator/runai-setup/self-hosted/k8s/preparations.md'
          - 'Install Backend' : 'Administrator/runai-setup/self-hosted/k8s/backend.md'
          - 'Install a Cluster' : 'Administrator/runai-setup/self-hosted/k8s/cluster.md'
          - 'Create Run:AI Projects' : 'Administrator/runai-setup/self-hosted/k8s/project-management.md'
          - 'Authentication' : 'Administrator/runai-setup/self-hosted/k8s/researcher-authentication.md'
          - 'LDAP Integration' : 'Administrator/runai-setup/self-hosted/k8s/ldap-integration.md'
          - 'Upgrade' : 'Administrator/runai-setup/self-hosted/k8s/upgrade.md'
          - 'Uninstall' : 'Administrator/runai-setup/self-hosted/k8s/uninstall.md'
        - 'OpenShift-based' :
          - 'Prerequisites' : 'Administrator/runai-setup/self-hosted/ocp/prerequisites.md'
          - 'Preperations' : 'Administrator/runai-setup/self-hosted/ocp/preparations.md'
          - 'Install Dependencies' : 'Administrator/runai-setup/self-hosted/ocp/ocp-dependencies.md'
          - 'Install Backend' : 'Administrator/runai-setup/self-hosted/ocp/backend.md'
          - 'Install a Cluster' : 'Administrator/runai-setup/self-hosted/ocp/cluster.md'
          - 'Create Run:AI Projects' : 'Administrator/runai-setup/self-hosted/ocp/project-management.md'
    #    - 'Airgapped Kubernetes' : 'k8s.md'
    - 'Researcher Setup' :
      - 'Introduction' : 'Administrator/Researcher-Setup/researcher-setup-intro.md'
      - 'Install the CLI' : 'Administrator/Researcher-Setup/cli-install.md'
      - 'Troubleshooting' : 'Administrator/Researcher-Setup/cli-troubleshooting.md'
      - 'Researcher UI' : 'Administrator/Researcher-Setup/researcher-ui-setup.md'
      - 'Use a Docker Registry with Credentials' : 'Administrator/Researcher-Setup/docker-registry-config.md'
      - 'Switch from Docker to Run:AI ' : 'Administrator/Researcher-Setup/docker-to-runai.md'
      - 'Group Nodes' : 'Administrator/Researcher-Setup/limit-to-node-group.md'
      - 'Use Secrets in Jobs' : 'Administrator/Researcher-Setup/use-secrets.md'
      - 'UI Templates' : 'Administrator/Researcher-Setup/templates.md'
    - 'Admin UI' :
      - 'Users' : 'Administrator/admin-ui-setup/admin-ui-users.md'
      - 'Projects' : 'Administrator/admin-ui-setup/project-setup.md'
      - 'Departments' : 'Administrator/admin-ui-setup/department-setup.md'
      - 'Dashboard Analysis' : 'Administrator/admin-ui-setup/dashboard-analysis.md'
    - 'Integrations' :
      - 'JupyterHub' : 'Administrator/integration/jupyterhub.md'
      - 'Airflow' : 'Administrator/integration/airflow.md' 
      - 'MLflow' : 'Administrator/integration/mlflow.md'
      - 'Kubeflow' : 'Administrator/integration/kubeflow.md'
    - 'Presentations' :
      - 'Administrator Onboarding' : 'Administrator/presentations/administrator-onboarding-presentation.md'
  - 'Researcher' :
    - 'Overview' : 'Researcher/overview-researcher.md'
    - 'Quickstart Guides' :
      - 'Run:AI Quickstart Guides' : 'Researcher/Walkthroughs/quickstart-overview.md'
      - 'Training' : 'Researcher/Walkthroughs/walkthrough-train.md'
      - 'Build' : 'Researcher/Walkthroughs/walkthrough-build.md'
      - 'Build with Connected Ports' : 'Researcher/Walkthroughs/walkthrough-build-ports.md'
      - 'GPU Fractions' : 'Researcher/Walkthroughs/walkthrough-fractions.md'
      - 'Distributed Training Workloads' : 'Researcher/Walkthroughs/walkthrough-distributed-training.md'
      - 'Hyperparameter Optimization' : 'Researcher/Walkthroughs/walkthrough-hpo.md'
      - 'Over-Quota, Basic Fairness & Bin-Packing' : 'Researcher/Walkthroughs/walkthrough-overquota.md'
      - 'Queue Fairness' : 'Researcher/Walkthroughs/walkthrough-queue-fairness.md'
      - 'Elasticity' : 'Researcher/Walkthroughs/walkthrough-elasticity.md'
      - 'Inference' : 'Researcher/Walkthroughs/quickstart-inference.md'
    - 'CLI Reference' :
      - 'Introduction' : 'Researcher/cli-reference/Introduction.md'
      - 'runai attach' : 'Researcher/cli-reference/runai-attach.md'
      - 'runai bash' : 'Researcher/cli-reference/runai-bash.md'
      - 'runai config' : 'Researcher/cli-reference/runai-config.md'
      - 'runai delete' : 'Researcher/cli-reference/runai-delete.md'
      - 'runai describe' : 'Researcher/cli-reference/runai-describe.md'
      - 'runai exec' : 'Researcher/cli-reference/runai-exec.md'
      - 'runai list' : 'Researcher/cli-reference/runai-list.md'
      - 'runai logs' : 'Researcher/cli-reference/runai-logs.md'
      - 'runai resume' : 'Researcher/cli-reference/runai-resume.md'
      - 'runai submit' : 'Researcher/cli-reference/runai-submit.md'
      - 'runai submit-mpi' : 'Researcher/cli-reference/runai-submit-mpi.md'
      - 'runai suspend' : 'Researcher/cli-reference/runai-suspend.md'
      - 'runai template' : 'Researcher/cli-reference/runai-template.md'
      - 'runai top node' : 'Researcher/cli-reference/runai-top-node.md'
      - 'runai top job' : 'Researcher/cli-reference/runai-top-job.md'
      - 'runai update' : 'Researcher/cli-reference/runai-update.md'
      - 'runai version' : 'Researcher/cli-reference/runai-version.md'
      - 'runai whoami' : 'Researcher/cli-reference/runai-whoami.md'
    - 'Best Practices' :
      - 'Bare-Metal to Docker Images' : 'Researcher/best-practices/bare-metal-to-docker-images.md'
      - 'Convert a Workload to Run Unattended' : 'Researcher/best-practices/convert-to-unattended.md'
      - 'Save Deep Learning Checkpoints' : 'Researcher/best-practices/save-dl-checkpoints.md'
      - 'Environment Variables' : 'Researcher/best-practices/env-variables.md'
    - 'Scheduling' :
      - 'Allocation of CPU and Memory' : 'Researcher/scheduling/allocation-of-cpu-and-memory.md'
      - 'The Run:AI Scheduler' : 'Researcher/scheduling/the-runai-scheduler.md'
      - 'Job Statuses' : 'Researcher/scheduling/job-statuses.md'
      - 'Automatically Delete Finished Workloads' : 'Researcher/scheduling/auto-delete-jobs.md'
    - 'Researcher Library' :
      - 'Overview' : 'Researcher/researcher-library/researcher-library-overview.md'
      - 'Elasticity' : 'Researcher/researcher-library/rl-elasticity.md'
      - 'Reporting' : 'Researcher/researcher-library/rl-reporting.md'
      - 'HPO' : 'Researcher/researcher-library/rl-hpo-support.md'
    - 'Presentations' :
      - 'Researcher Onboarding' : 'Researcher/presentations/researcher-onboarding-presentation.md'
    - 'Tools' :
      - 'Visual Studio Code' : 'Researcher/tools/dev-vscode.md'    
      - 'PyCharm' : 'Researcher/tools/dev-pycharm.md'    
      - 'X11 & PyCharm' : 'Researcher/tools/dev-x11forward-pycharm.md'  
      - 'Jupyter Noteook' :  'Researcher/tools/dev-jupyter.md'
      - 'TensorBoard' :  'Researcher/tools/dev-tensorboard.md'  
  - 'Developer' :
    - 'Overview' : 'developer/overview-developer.md'
    - 'Researcher REST API' : 
        - 'Overview' : 'developer/researcher-rest-api/overview.md'
        - 'Submit a Job' :  'developer/researcher-rest-api/rest-submit.md'
        - 'Delete a Job' :  'developer/researcher-rest-api/rest-delete.md'
        - 'Get a list of Jobs' :  'developer/researcher-rest-api/rest-list-jobs.md'
        - 'Get a list of Projects' :  'developer/researcher-rest-api/rest-list-projects.md'
    - 'Researcher Kubernetes API' : 
        - 'Submit a Job via YAML' : 'developer/k8s-api/launch-job-via-yaml.md'
        - 'Submit a Job via Kubernetes API' : 'developer/k8s-api/launch-job-via-kubernetes-api.md'
    - 'Administrator REST API' : 
        - 'Overview' : 'developer/admin-rest-api/overview.md'
        - 'Projects' :  'developer/admin-rest-api/projects.md'
        - 'Departments' :  'developer/admin-rest-api/departments.md'
        - 'Users' :  'developer/admin-rest-api/users.md'
        - 'Node Types' :  'developer/admin-rest-api/node-types.md'
        - 'Clusters' :  'developer/admin-rest-api/clusters.md'
    - 'Inference' :
      - 'Overview' : 'developer/inference/overview.md' 
      - 'Setup' : 'developer/inference/setup.md' 
      - 'Submit via CLI' : 'developer/inference/submit-via-cli.md' 
      - 'Submit via YAML' : 'developer/inference/submit-via-yaml.md' 
