site_name: Run:AI Documentation Library
site_url: https://run.ai
copyright: Copyright © 2020 Run:AI
google_analytics:
  - UA-122651141-1
  - auto

#repo_url: https://github.com/run-ai/docs/


docs_dir: docs
theme:
  name: material
#  custom_dir: custom_theme
#  name: mkdocs
#  name: readthedocs
#  name: ivory
#  name: bootstrap4
#  name: gitbook
#  name: 'rtd-dropdown'
 # palette:
  #  scheme: slate
#     primary: indigo
#     accent: red
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  language: en
  favicon: images/favicon.ico
  logo: images/runai-logo2.svg
  features:
    - tabs
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: True
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/runailabs
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/runailabs/

nav:
  - Home: 'index.md'
  - 'Administrator' :
    - 'Cluster Setup' :
      - 'Introduction' : 'Administrator/Cluster-Setup/Cluster-Setup-Start-Here.md'
      - 'Cluster Prerequisites' : 'Administrator/Cluster-Setup/Run-AI-GPU-Cluster-Prerequisites.md'
      - 'Cluster Installation' : 'Administrator/Cluster-Setup/Installing-Run-AI-on-an-on-premise-Kubernetes-Cluster.md'
      - 'Troubleshooting a Cluster Installation' : 'Administrator/Cluster-Setup/Troubleshooting-a-Run-AI-Cluster-Installation.md'
      - 'Upgrading a Cluster Installation' : 'Administrator/Cluster-Setup/Upgrading-Cluster-Install.md'
      - 'Deleting a Cluster Installation' : 'Administrator/Cluster-Setup/Deleting-Cluster-Install.md'
      - 'Configuring an Ingress Service' : 'Administrator/Cluster-Setup/Exposing-Cluster-Services-via-Ingress.md'
      - 'Exposing Container Ports using Ingress' : 'Administrator/Cluster-Setup/Exposing-Ports-from-Researcher-Containers-using-Ingress.md'
      - 'Configuring an Internet Proxy Server ' : 'Administrator/Cluster-Setup/Installing-Run-AI-with-an-Internet-Proxy-Server-.md'
      - 'Kubernetes Cluster Configuration Best Practices' : 'Administrator/Cluster-Setup/Kubernetes-Cluster-Configuration-Best-Practices.md'
      - 'Authentication and Authorization' : 'Administrator/Cluster-Setup/Use-OpenID-Connect-LDAP-or-SAML-for-Authentication-and-Authorization-.md'
      - 'Limit Install to Specific Nodes' : 'Administrator/Cluster-Setup/limit-runai-install-to-specific-nodes.md'
      - 'Enforce non-root Containers' : 'Administrator/Cluster-Setup/enforce-run-as-user.md'
    - 'Researcher Setup' :
      - 'Introduction' : 'Administrator/Researcher-Setup/Researcher-Setup-Start-Here.md'
      - 'Installing the Command Line Interface' : 'Administrator/Researcher-Setup/Installing-the-Run-AI-Command-Line-Interface.md'
      - 'Troubleshooting a CLI Installation' : 'Administrator/Researcher-Setup/Troubleshooting-a-CLI-installation.md'
      - 'Limit Workloads to a Specific Node Group' : 'Administrator/Researcher-Setup/Limit-a-Workload-to-a-Specific-Node-Group.md'
      - 'Using a Docker Registry with Credentials' : 'Administrator/Researcher-Setup/Using-a-Docker-Registry-with-Credentials.md'
      - 'Switch from working with Docker to working with Run:AI ' : 'Administrator/Researcher-Setup/Switch-from-working-with-Docker-to-working-with-Run-AI-.md'
      - 'Limit Workloads to Specific GPUs in Specific Nodes' : 'Administrator/Researcher-Setup/Limit-the-Run-AI-Scheduler-to-Specific-GPUs-in-Specific-Nodes.md'
      - 'Configure Command Line Interface Templates' : 'Administrator/Researcher-Setup/Configure-Command-Line-Interface-Templates.md'
    - 'Presentations' :
      - 'Administrator Onboarding' : 'Administrator/Presentations/Administrator-Onboarding-Presentation.md'
    - 'Admin User Interface Setup' :
      - 'Working with Projects' : 'Administrator/Admin-User-Interface-Setup/Working-with-Projects.md'
      - 'Managing Admin UI Users' : 'Administrator/Admin-User-Interface-Setup/Adding-Updating-and-Deleting-Admin-UI-Users.md'
    - 'Miscellaneous' :
      - 'Using Rancher to submit workloads' : 'Administrator/Miscellaneous/Launch-Workloads-using-Rancher-User-Interface.md'      
  - 'Researcher' :
    - 'Walkthroughs' :
      - 'Run:AI Walkthroughs' : 'Researcher/Walkthroughs/Run-AI-Walkthroughs.md'
      - 'Launch Interactive Build Workloads' : 'Researcher/Walkthroughs/Walkthrough-Start-and-Use-Interactive-Build-Workloads-.md'
      - 'Launch Interactive Build Workloads with Connected Ports' : 'Researcher/Walkthroughs/Walkthrough-Launch-an-Interactive-Build-Workload-with-Connected-Ports.md'
      - 'Launch Unattended Training Workloads' : 'Researcher/Walkthroughs/Walkthrough-Launch-Unattended-Training-Workloads-.md'
      - 'Launch Workloads with GPU Fractions' : 'Researcher/Walkthroughs/Walkthrough-Using-GPU-Fractions.md'
      - 'Launch Distributed Training Workloads' : 'Researcher/Walkthroughs/Walkthrough-Running-Distributed-Training.md'
    - 'CLI Reference' :
      - 'Introduction' : 'Researcher/Command-Line-Interface-API-Reference/Introduction.md'
      - 'runai bash' : 'Researcher/Command-Line-Interface-API-Reference/runai-bash.md'
      - 'runai exec' : 'Researcher/Command-Line-Interface-API-Reference/runai-exec.md'
      - 'runai delete' : 'Researcher/Command-Line-Interface-API-Reference/runai-delete.md'
      - 'runai get' : 'Researcher/Command-Line-Interface-API-Reference/runai-get.md'
      - 'runai list' : 'Researcher/Command-Line-Interface-API-Reference/runai-list.md'
      - 'runai logs' : 'Researcher/Command-Line-Interface-API-Reference/runai-logs.md'
      - 'runai submit' : 'Researcher/Command-Line-Interface-API-Reference/runai-submit.md'
      - 'runai submit-mpi' : 'Researcher/Command-Line-Interface-API-Reference/runai-submit-mpi.md'
      - 'runai top node' : 'Researcher/Command-Line-Interface-API-Reference/runai-top-node.md'
      - 'runai update' : 'Researcher/Command-Line-Interface-API-Reference/runai-update.md'
      - 'runai template' : 'Researcher/Command-Line-Interface-API-Reference/runai-template.md'
    - 'Command Line Interface' :
      - 'Job Statuses' : 'Researcher/Command-Line-Interface/Job-Statuses.md'
      - 'Automatically Delete Finished Workloads' : 'Researcher/Command-Line-Interface/Automatically-Delete-Jobs-After-Job-Finish.md'
    - 'Image Creation Best Practices' :
      - 'From Bare-Metal to using Docker Images' : 'Researcher/Image-Creation-Best-Practices/From-Bare-Metal-to-using-Docker-Images.md'
      - 'Converting your Workload to run Unattended' : 'Researcher/Image-Creation-Best-Practices/Converting-your-Workload-to-use-Unattended-Training-Execution.md'
      - 'Saving Deep Learning Checkpoints' : 'Researcher/Image-Creation-Best-Practices/Saving-Deep-Learning-Checkpoints.md'
    - 'Presentations' :
      - 'Researcher Onboarding' : 'Researcher/Presentations/Researcher-Onboarding-Presentation.md'
    - 'Scheduling' :
      - 'Allocation of CPU and Memory' : 'Researcher/Scheduling/Allocation-of-CPU-and-Memory.md'
      - 'The Run:AI Scheduler' : 'Researcher/Scheduling/The-Run-AI-Scheduler.md'
    - 'Run:AI Researcher Library' :
      - 'The Researcher Library' : 'Researcher/Run-AI-Researcher-Library/The-Run-AI-Researcher-Library.md'
      - 'Elasticity: Dynamically Stretch/Compress Workloads GPU Quota' : 'Researcher/Run-AI-Researcher-Library/Elasticity-Dynamically-Stretch-Compress-Jobs-According-to-GPU-Availability.md'
      - 'Reporting via the Researcher Library  ' : 'Researcher/Run-AI-Researcher-Library/Reporting-via-the-Run-AI-Researcher-Library-.md'

  - 'Product' :
    - 'Whats New' : 'Product/Whats-New.md'
