site_name: Run:AI
copyright:  All rights reserved Run:AI 2020
#google_analytics:
repo_url: https://github.com/run-ai/docs/

#docs_dir: 
theme:
#  name: mkdocs
  name: material
#  name: readthedocs
#  name: ivory
#  name: bootstrap4
#  name: gitbook
#  name: 'rtd-dropdown'

  favicon: images/favicon.png
  logo: images/runai-logo.svg
  features:
    - tabs
plugins:
  - search
  - minify:
      minify_html: true
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: True


nav:
  - Home: 'index.md'
  - 'Administrator' :
    - 'Cluster Setup' :
      - 'Cluster Setup - Start Here' : 'Administrator/Cluster-Setup/Cluster-Setup-Start-Here.md'
      - 'Run:AI GPU Cluster Prerequisites' : 'Administrator/Cluster-Setup/Run-AI-GPU-Cluster-Prerequisites.md'
      - 'Installing Run:AI on an on-premise Kubernetes Cluster' : 'Administrator/Cluster-Setup/Installing-Run-AI-on-an-on-premise-Kubernetes-Cluster.md'
      - 'Outbound URL Access Requirements' : 'Administrator/Cluster-Setup/Outbound-URL-Access-Requirements.md'
      - 'Troubleshooting a Run:AI Cluster Installation' : 'Administrator/Cluster-Setup/Troubleshooting-a-Run-AI-Cluster-Installation.md'
      - 'Use OpenID Connect, LDAP or SAML for Authentication and Authorization ' : 'Administrator/Cluster-Setup/Use-OpenID-Connect-LDAP-or-SAML-for-Authentication-and-Authorization-.md'
      - 'Exposing Ports from Researcher Containers using Ingress' : 'Administrator/Cluster-Setup/Exposing-Ports-from-Researcher-Containers-using-Ingress.md'
      - 'Upgrading and Deleting a Run:AI Cluster Installation' : 'Administrator/Cluster-Setup/Upgrading-and-Deleting-a-Run-AI-Cluster-Installation.md'
      - 'Exposing Cluster Services via Ingress' : 'Administrator/Cluster-Setup/Exposing-Cluster-Services-via-Ingress.md'
      - 'Installing Run:AI with an Internet Proxy Server ' : 'Administrator/Cluster-Setup/Installing-Run-AI-with-an-Internet-Proxy-Server-.md'
      - 'Kubernetes Cluster Configuration Best Practices' : 'Administrator/Cluster-Setup/Kubernetes-Cluster-Configuration-Best-Practices.md'
    - 'Researcher Setup' :
      - 'Researcher Setup - Start Here' : 'Administrator/Researcher-Setup/Researcher-Setup-Start-Here.md'
      - 'Installing the Run:AI Command Line Interface' : 'Administrator/Researcher-Setup/Installing-the-Run-AI-Command-Line-Interface.md'
      - 'Troubleshooting a CLI installation' : 'Administrator/Researcher-Setup/Troubleshooting-a-CLI-installation.md'
      - 'Limit a Workload to a Specific Node Group' : 'Administrator/Researcher-Setup/Limit-a-Workload-to-a-Specific-Node-Group.md'
      - 'Switch from working with Docker to working with Run:AI ' : 'Administrator/Researcher-Setup/Switch-from-working-with-Docker-to-working-with-Run-AI-.md'
      - 'Limit the Run:AI Scheduler to Specific GPUs in Specific Nodes' : 'Administrator/Researcher-Setup/Limit-the-Run-AI-Scheduler-to-Specific-GPUs-in-Specific-Nodes.md'
      - 'Using a Docker Registry with Credentials' : 'Administrator/Researcher-Setup/Using-a-Docker-Registry-with-Credentials.md'
      - 'Configure Command Line Interface Templates' : 'Administrator/Researcher-Setup/Configure-Command-Line-Interface-Templates.md'
    - 'Presentations' :
      - 'Administrator Onboarding Presentation' : 'Administrator/Presentations/Administrator-Onboarding-Presentation.md'
    - 'Admin User Interface Setup' :
      - 'Working with Projects' : 'Administrator/Admin-User-Interface-Setup/Working-with-Projects.md'
      - 'Adding, Updating and Deleting Admin UI Users' : 'Administrator/Admin-User-Interface-Setup/Adding-Updating-and-Deleting-Admin-UI-Users.md'
    - 'Miscellaneous ' :
      - 'Launch Workloads using Rancher User Interface' : 'Administrator/Miscellaneous-/Launch-Workloads-using-Rancher-User-Interface.md'  
  - 'Researcher' :
    - 'Presentations' :
      - 'Researcher Onboarding Presentation' : 'Researcher/Presentations/Researcher-Onboarding-Presentation.md'
    - 'Scheduling' :
      - 'Allocation of CPU and Memory' : 'Researcher/Scheduling/Allocation-of-CPU-and-Memory.md'
      - 'The Run:AI Scheduler' : 'Researcher/Scheduling/The-Run-AI-Scheduler.md'
    - 'Run:AI Researcher  Library' :
      - 'The Run:AI Researcher Library' : 'Researcher/Run-AI-Researcher-Library/The-Run-AI-Researcher-Library.md'
      - 'Elasticity: Dynamically Stretch/Compress Jobs According to GPU Availability' : 'Researcher/Run-AI-Researcher-Library/Elasticity-Dynamically-Stretch-Compress-Jobs-According-to-GPU-Availability.md'
      - 'Reporting via the Run:AI Researcher Library  ' : 'Researcher/Run-AI-Researcher-Library/Reporting-via-the-Run-AI-Researcher-Library-.md'
    - 'Image Creation Best Practices' :
      - 'From Bare-Metal to using Docker Images' : 'Researcher/Image-Creation-Best-Practices/From-Bare-Metal-to-using-Docker-Images.md'
      - 'Converting your Workload to use Unattended "Training" Execution' : 'Researcher/Image-Creation-Best-Practices/Converting-your-Workload-to-use-Unattended-Training-Execution.md'
      - 'Saving Deep Learning Checkpoints' : 'Researcher/Image-Creation-Best-Practices/Saving-Deep-Learning-Checkpoints.md'
    - 'Command Line Interface' :
      - 'Migrating to Permission-Aware CLI' : 'Researcher/Command-Line-Interface/Migrating-to-Permission-Aware-CLI.md'
      - 'Automatically Delete Jobs After Job Finish' : 'Researcher/Command-Line-Interface/Automatically-Delete-Jobs-After-Job-Finish.md'
    - 'Walkthroughs' :
      - 'Walkthrough: Launch Unattended Training Workloads ' : 'Researcher/Walkthroughs/Walkthrough-Launch-Unattended-Training-Workloads-.md'
      - 'Walkthrough: Start and Use Interactive Build Workloads ' : 'Researcher/Walkthroughs/Walkthrough-Start-and-Use-Interactive-Build-Workloads-.md'
      - 'Run:AI Walkthroughs' : 'Researcher/Walkthroughs/Run-AI-Walkthroughs.md'
      - 'Walkthrough: Using GPU Fractions' : 'Researcher/Walkthroughs/Walkthrough-Using-GPU-Fractions.md'
      - 'Walkthrough: Launch an Interactive Build Workload with Connected Ports' : 'Researcher/Walkthroughs/Walkthrough-Launch-an-Interactive-Build-Workload-with-Connected-Ports.md'
      - 'Walkthrough: Running Distributed Training' : 'Researcher/Walkthroughs/Walkthrough-Running-Distributed-Training.md'
    - 'Command Line Interface - API Reference' :
      - 'runai delete' : 'Researcher/Command-Line-Interface-API-Reference/runai-delete.md'
      - 'Introduction' : 'Researcher/Command-Line-Interface-API-Reference/Introduction.md'
      - 'runai get' : 'Researcher/Command-Line-Interface-API-Reference/runai-get.md'
      - 'runai list' : 'Researcher/Command-Line-Interface-API-Reference/runai-list.md'
      - 'runai logs' : 'Researcher/Command-Line-Interface-API-Reference/runai-logs.md'
      - 'runai top node' : 'Researcher/Command-Line-Interface-API-Reference/runai-top-node.md'
      - 'runai update' : 'Researcher/Command-Line-Interface-API-Reference/runai-update.md'
      - 'runai template' : 'Researcher/Command-Line-Interface-API-Reference/runai-template.md'
      - 'runai submit' : 'Researcher/Command-Line-Interface-API-Reference/runai-submit.md'
      - 'runai submit-mpi' : 'Researcher/Command-Line-Interface-API-Reference/runai-submit-mpi.md'
      - 'runai bash' : 'Researcher/Command-Line-Interface-API-Reference/runai-bash.md'
      - 'runai exec' : 'Researcher/Command-Line-Interface-API-Reference/runai-exec.md'
  - 'Product' :
    - 'Documents' :
      - 'Whats New' : 'Product/Documents/What-s-New.md'
