apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projects.run.ai
spec:
  group: run.ai
  version: v1
  scope: Cluster
  names:
    kind: Project
    plural: projects
    singular: project
    shortNames:
      - rp
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            department:
              type: string
            deservedGpus:
              format: float
              type: number
            maxAllowedGpus:
              format: float
              type: number
            interactiveJobTimeLimitSecs:
              format: int64
              type: integer
            nodeAffinityInteractive:
              items:
                type:
                  string
              type: array
            nodeAffinityTrain:
              items:
                type:
                  string
              type: array
            swapEnabled:
              type: boolean
          type: object
      type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.incubator.k8s.io
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: Queue
    plural: queues
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deservedGpus:
              format: float
              type: number
            maxAllowedGpus:
              format: float
              type: number
            interactiveJobTimeLimitSecs:
              format: int64
              type: integer
            nodeAffinityInteractive:
              items:
                type:
                  string
              type: array
            nodeAffinityTrain:
              items:
                type:
                  string
              type: array
            swapEnabled:
              type: boolean
          type: object
      type: object
  version: v1alpha1
