apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: departments.scheduling.incubator.k8s.io
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: Department
    plural: departments
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deservedGpus:
              format: float
              type: number
          type: object
      type: object
  version: v1alpha1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: runaijobs.run.ai
spec:
    group: run.ai
    version: v1
    scope: Namespaced
    names:
        plural:  runaijobs
        singular: runaijob
        kind: RunaiJob
        shortNames:
        - rj
    subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projects.run.ai
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  group: run.ai
  version: v1
  scope: Cluster
  names:
    kind: Project
    plural: projects
    singular: project
    shortNames:
      - rp
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            department:
              type: string
            deservedGpus:
              format: float
              type: number
            interactiveJobTimeLimitSecs:
              format: int64
              type: integer
            nodeAffinityInteractive:
              items:
                type:
                  string
              type: array
            nodeAffinityTrain:
              items:
                type:
                  string
              type: array
          type: object
      type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.incubator.k8s.io
  annotations:
    "helm.sh/hook-weight": "2"
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: PodGroup
    plural: podgroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            minMember:
              format: int32
              type: integer
            queue:
              type: string
            priorityClassName:
              type: string
          type: object
        status:
          properties:
            succeeded:
              format: int32
              type: integer
            failed:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.incubator.k8s.io
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: Queue
    plural: queues
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deservedGpus:
              format: float
              type: number
            interactiveJobTimeLimitSecs:
              format: int64
              type: integer
            nodeAffinityInteractive:
              items:
                type:
                  string
              type: array
            nodeAffinityTrain:
              items:
                type:
                  string
              type: array
          type: object
      type: object
  version: v1alpha1
