apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runai-project-controller-cluster-secret
rules:
  - apiGroups:
      - run.ai
    resources:
      - projects
      - projects/finalizers
    verbs:
      - '*'
  - apiGroups:
      - scheduling.incubator.k8s.io
    resources:
      - queues
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runai-project-controller-cluster-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: runai-project-controller-cluster-secret
subjects:
  - kind: ServiceAccount
    name: runai-project-controller
    namespace: runai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runai-project-controller-cluster-secret-per-project
rules:
  - apiGroups:
      - ""
    resourceNames:
      - default
    resources:
      - serviceaccounts
    verbs:
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
      - secrets/finalizers
    verbs:
      - update
      - create
      - delete
