name: publish docs CI to staging 

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'Version number from branch / "main" for latest'
        default: master
      bucket_name:
        required: false
        description: 'bucket name you want to upload the content'
        default: runai-docs-staging

jobs:
  install_dependencies_and_deploy:
    name: install dependencies and deploy latest changes to staging
    runs-on: ubuntu-latest
    steps:
        - name: checkout latest
          uses: actions/checkout@v3
          with:
            ref: ${{ inputs.version }}
            fetch-depth: 0
        - name: python setup
          uses: actions/setup-python@v4
          with:
            python-version: 3.x
        - uses: actions/cache@v2
          with:
            key: ${{ github.ref }}
            path: .cache
        - name: build
          run: pip3 install -r requirements.txt

        - name: Build
          run: | 
            mkdocs build

        - name: build and copy docs
          uses: gameclosure/mkdocs-publish-s3-action@master
          env:
            S3_PATH: s3://${{ inputs.bucket_name }}/
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            CHANGELOG: true # generate a changelog file out of Github release notes
            CHANGELOG_STRIP_PATTERN: https?:\/\/[^ ]+ # optional strip pattern to run on the generated changelog
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required if generating a changelog
            TYPEDOC: true # generate Typescript API documentation with typedoc