name: docs CI 

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'version name'
        default: "latest"
        type: string

  push:
    branches:
      - "master"
  # pull_request:
  #   branches:
  #     - "master"


jobs:
  install_dependencies_and_deploy:
    name: install dependencies and deploy latest changes to prod
    runs-on: ubuntu-latest
    steps:
        - name: checkout latest
          uses: actions/checkout@v3

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies

        - name: install dependencies
          run: |
           pip3 install -r requirements.txt
        
        - name: deploy mkdocs
          run: | 
            mkdocs gh-deploy --force




        